### ISSUE TITLE
Background of magnifying glass in Plugin page is gray (instead of transparent)

### ISSUE THREAD

**Issue by fnurl** [playerofgames/logseq-mia-theme#14]
Thanks for the theme! I just noticed that the background of the magnifying glass in the seach field on the plugin view (installed/marketplace) is gray from what I can see line 260 in `mia_base.css`.

I had to add the following to my custom.css to get rid of it.

```css
.cp__plugins-page .search-ctls small.absolute.s1 {
  background-color: transparent !important;
}
```
