### ISSUE TITLE
Add style for "DOING" and "WAITING"

### ISSUE THREAD

**Issue by brunoperdigao** [playerofgames/logseq-mia-theme#19]
Hi, 
I'd like to propose to add a gray fill for "DOING" keyword and a yellow fill for "WAITING". Here is an example from another theme:
![image](https://github.com/playerofgames/logseq-mia-theme/assets/57102715/4b41e31f-c9ed-416a-b2b7-e467e30fd9cb)

**Comment by playerofgames** [comment]
This could be achieved using custom CSS. Have you created CSS to do this?

**Comment by brunoperdigao** [comment]
Yes, after a while I was able to add this to my `custom.css`:

``` css
.doing>.form-checkbox {
  background-color: var(--ls-quaternary-background-color);
}

.waiting>.form-checkbox {
  background-color: var(--ls-page-mark-bg-color);
}
```
